# Generated by Django 2.2.3 on 2019-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverresume',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
