# Generated by Django 2.2.3 on 2019-11-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0004_auto_20191120_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('key_person_name', models.CharField(max_length=200)),
                ('key_person_contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
