# Generated by Django 2.2.3 on 2019-11-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0005_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
